//! Regenerate compact Unicode property tables using the pinned dev-only regex data.
use regex::Regex;
fn main() {
    println!("// Generated by examples/pretext_unicode.rs; Unicode properties from Cargo.lock's regex-syntax.\n// See tests/fixtures/pretext/LICENSE for the translated algorithm's attribution.");
    for (name, pattern) in [
        ("MARK", r"\p{M}"),
        ("DECIMAL", r"\p{Nd}"),
        ("ARABIC", r"\p{Script=Arabic}"),
        ("PUNCT_SYMBOL_PRIVATE", r"[\p{P}\p{S}\p{Co}]"),
        ("EMOJI_PRESENTATION", r"\p{Emoji_Presentation}"),
        (
            "MAYBE_EMOJI",
            r"[\p{Emoji_Presentation}\p{Extended_Pictographic}\p{Regional_Indicator}\u{FE0F}\u{20E3}]",
        ),
    ] {
        let regex = Regex::new(pattern).unwrap();
        let mut ranges = Vec::<(u32, u32)>::new();
        for code in 0..=0x10ffff {
            let Some(ch) = char::from_u32(code) else {
                continue;
            };
            let mut buffer = [0; 4];
            if !regex.is_match(ch.encode_utf8(&mut buffer)) {
                continue;
            }
            if let Some(last) = ranges.last_mut().filter(|last| last.1 + 1 == code) {
                last.1 = code;
            } else {
                ranges.push((code, code));
            }
        }
        println!("#[rustfmt::skip]\npub const {name}: &[(u32,u32)] = &{ranges:?};");
    }
}
